### ISSUE TITLE
extend proxy

### ISSUE THREAD

**Issue by vtolstov** [jsimonetti/go-spice#1]
great to see this package, sometimes ago i'm try to do something like this, but don't have enough time to finish.

What do you think about proxy via grpc? I don't have ip address of compute nodes, but on each compute node i have microservice that connected to service mesh. So from gateway i can reach this service via grpc.
I have grpc steam with such methods:
```
    Send(interface{}) error
    Recv(interface{}) error
    Error() error
    Close() error
``` 

how to connect this stream with you package? as i understand i need something like custom dialer, but don't fully understand how to do that.

**Comment by jsimonetti** [comment]
Hi,

This would pose some difficulties. This package proxies the direct spice protocol and assumes the compute nodes' spice port is accessible directly by the proxy. This means that both the tenant as the compute side of the proxy talk the spice protocol.

You might be able to modify this package to your liking and do a new implementation of the `computeHandshake` (https://github.com/jsimonetti/go-spice/blob/master/compute.go#L19) that uses your grpc stream.

If your grpc stream is just an encapsulation of the original spice connection to the qemu HV, then you might build a custom dialer that returns a `net.Conn` that talks the spice protocol (in the background encapsulating into grpc). I don't have enough knowledge about your environment to properly assess if this is a possibility.

**Comment by vtolstov** [comment]
Thanks for answer, my grpc stream encapsulate original spice connection to qemu port (unix socket).
So nice, i can use custom dialer. Thanks!

**Comment by jsimonetti** [comment]
Hi,
I am curious to learn if you made this to work.
I would be very interested to see how you use this package.
