### ISSUE TITLE
Provide virt-viewer example

### ISSUE THREAD

**Issue by ifoo** [jsimonetti/go-spice#2]
After reading the source code and comments, it's not quite clear to me how to provide a 'token' with a standard SPICE client (like virt-viewer).
In the example application, the comment says:

> a) Tenant authenticates using token '123e4567:secretpw'

How exactly can I provide a token in virt-viewer?

Could you provide an example on how to connect with something like virt-viewer, remote-viewer or spicy?

**Comment by jsimonetti** [comment]
Hi,

There are several ways of providing the token. The easiest is to let your users download a special virt-viewer file from a web location (works with virt-viewer and remote-viewer when properly associated; unsure about spicy):

```go
vv := fmt.Sprintf("[virt-viewer]\ntype=spice\nhost=%s\nport=%d\npassword=%s\ndelete-this-file=1",
  spiceProxyHost, spiceProxyPort, token)
w.Header().Set("Content-Type", "application/x-virt-viewer")
```

The other option is letting people connect to the proxy manually and your virt-viewer wil prompt the user for a password token.
This is less user-friendly, as the token should be regenerated after every use to enforce a one-time usage of tokens.

Edit:
FYI, a token in the SPICE protocol is called a password in the virt-viewer application.
